import React, { useState } from 'react';
import { FileText, Copy, Check, Printer, X, Download, Code, Sparkles } from 'lucide-react';
import { ClinicianApproval, PatientDigitalTwin, SessionRunResult } from '../agents/types';
import { fhirExportService } from '../services/FhirExportService';

interface ClinicalReportModalProps {
  digitalTwin: PatientDigitalTwin;
  sessionResult: SessionRunResult | null;
  clinicianApproval: ClinicianApproval | null;
  onClose: () => void;
}

export const ClinicalReportModal: React.FC<ClinicalReportModalProps> = ({
  digitalTwin,
  sessionResult,
  clinicianApproval,
  onClose
}) => {
  const [activeTab, setActiveTab] = useState<'markdown' | 'fhir'>('markdown');
  const [copied, setCopied] = useState(false);
  const hasBoundClinicianApproval = Boolean(
    clinicianApproval &&
    sessionResult?.sessionId &&
    clinicianApproval.sessionId === sessionResult.sessionId &&
    clinicianApproval.patientId === digitalTwin.patientId
  );
  const supervisoryStatus = hasBoundClinicianApproval
    ? `Clinician approved by ${clinicianApproval!.approvedBy} at ${new Date(clinicianApproval!.approvedAt).toLocaleString()} (session ${clinicianApproval!.sessionId})`
    : sessionResult?.safety.actuationPermitted
      ? 'Safety-agent autonomous clearance; no clinician signature recorded'
      : sessionResult?.safety.therapistApprovalRequired
        ? 'Pending clinician approval; actuation remains blocked'
        : 'Safety veto active; clinician approval cannot override the current boundary';

  const reportText = `# NeuroBridge SenseAssist - Quantitative Clinical Neuro-Rehabilitation Report

**Generated Date**: ${new Date().toLocaleDateString()}
**Patient Name**: ${digitalTwin.name}
**Patient ID**: ${digitalTwin.patientId}
**Age**: ${digitalTwin.age}
**Diagnosis**: ${digitalTwin.clinicalCondition}
**Sessions Completed**: ${digitalTwin.sessionsCompleted}

---

## 1. Longitudinal Communication Trajectory
- **Speaking Velocity**: ${sessionResult?.biomarkers.speakingRateWpm || 76} WPM (+${sessionResult?.progress.wpmImprovementPercent || 28}% vs baseline)
- **Mean Pause Latency**: ${sessionResult?.biomarkers.meanPauseDurationSec || 1.3} sec (-${sessionResult?.progress.pauseReductionPercent || 42}% reduction in motor hesitation)
- **Rhythm Stability Index**: ${Math.round((sessionResult?.biomarkers.rhythmStabilityIndex || 0.65) * 100)}%
- **Segmental Phoneme Accuracy**: ${Math.round((sessionResult?.phenotype.motorPlanningScore || 0.72) * 100)}%

---

## 2. Autonomous Deficit Phenotyping
- **Primary Deficit**: ${sessionResult?.phenotype.primaryDeficit || 'Phonemic Articulatory Substitution & Initiation Hesitation'}
- **Acoustic Differential**: Cognitive word retrieval is intact. Initiation delay stems from pre-motor planning blocks.
- **Sensory Entrainment Effect**: Demonstrates strong sub-cortical synchronization response to rhythmic tactile pacing.

---

## 3. Prescribed Adaptive Sensory-Motor Intervention
- **Pacing Cadence**: ${digitalTwin.preferredBpm} BPM
- **Haptic Wearable Protocol**: 1-2-3-4 Tactile Pulse @ 65% Intensity
- **Visual Motor Cue**: Dynamic Lip/Tongue Articulatory Contours
- **Supervisory Status**: ${supervisoryStatus}

---

## 4. Global Health Classification & Interoperability
- **WHO ICF Code**: ICF b320 (Articulation) & ICF b330 (Fluency and Rhythm)
- **HL7® FHIR® Release 4**: Prototype FHIR R4-formatted DiagnosticReport & CarePlan export (Validation Pending - Non-Device CDS Research Prototype).

*Report automatically generated by NeuroBridge SenseAssist Autonomous Clinical Reasoning Prototype. For clinician supervisory review only.*
`;

  const fhirBundle = fhirExportService.generateFhirBundle(digitalTwin, sessionResult);
  const fhirJson = JSON.stringify(fhirBundle, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(activeTab === 'markdown' ? reportText : fhirJson);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadFhir = () => {
    const blob = new Blob([fhirJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fhir_report_${digitalTwin.patientId}_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-in fade-in">
      <div className="w-full max-w-3xl max-h-[90vh] rounded-3xl bg-slate-900 border border-slate-700 shadow-2xl p-6 flex flex-col space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-3">
            <div className="flex rounded-lg bg-slate-950 p-1 border border-slate-800">
              <button
                onClick={() => setActiveTab('markdown')}
                className={`flex items-center space-x-1.5 px-3 py-1 rounded-md text-xs font-semibold transition-colors ${
                  activeTab === 'markdown' ? 'bg-teal-500 text-slate-950' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Clinical Report</span>
              </button>
              <button
                onClick={() => setActiveTab('fhir')}
                className={`flex items-center space-x-1.5 px-3 py-1 rounded-md text-xs font-semibold transition-colors ${
                  activeTab === 'fhir' ? 'bg-teal-500 text-slate-950' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Code className="w-3.5 h-3.5" />
                <span>HL7 FHIR (JSON)</span>
              </button>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            {activeTab === 'fhir' && (
              <button
                onClick={handleDownloadFhir}
                className="px-3 py-1.5 rounded-lg bg-cyan-500 text-slate-950 text-xs font-bold flex items-center space-x-1.5 shadow-md shadow-cyan-500/20"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download FHIR .json</span>
              </button>
            )}
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center space-x-1.5 border border-slate-700"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-lg bg-teal-500 text-slate-950 text-xs font-bold flex items-center space-x-1.5 shadow-md shadow-teal-500/20"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto rounded-xl bg-slate-950 p-6 border border-slate-800 font-sans text-xs text-slate-200 leading-relaxed whitespace-pre-wrap">
          {activeTab === 'markdown' ? (
            reportText
          ) : (
            <pre className="font-mono text-cyan-300 text-[11px]">{fhirJson}</pre>
          )}
        </div>
      </div>
    </div>
  );
};
